# Generated by Django 4.0.4 on 2022-04-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
