# Generated by Django 4.0.4 on 2022-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_control', '0002_user_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
